### ISSUE TITLE
After update helix3 to 1.5 above and below positions disappeared

### ISSUE THREAD

**Issue by ilmiositojoomla** [JoomShaper/Helix3#45]
After update helix3 to 1.5 I tried to re-add above and below position using those instrucion https://www.joomshaper.com/documentation/helix3/custom-module-above-and-below-component But on Helix3 1.5 I did not find the jdoc:include rows in plugins/system/helix3/core/helix3.php file. 
How can I proceed? 
Thank you. 
cmc

**Comment by pepperstreet** [comment]
The mentioned [documentation article](https://www.joomshaper.com/documentation/helix3/custom-module-above-and-below-component) seem to have a small update regarding Helix3 v1.5 

New location and file is here:
`templates/shaper_TemplateName/component.php`

**Comment by ilmiositojoomla** [comment]
I made changes in component.php and in templateDetails.xml, BUT the module in "above" position don't show. The same configuration on helix3 works well. Maybe I have to modify some other files on helix3 1.5?
Thank you.
cmc

**Comment by pepperstreet** [comment]
@ilmiositojoomla Apparently you are right. It seems to be a wrong info. I have also wondered about the component.php, because usually... this file is called by a special URL parameter. So, forget about it ;) 

--- 

I guess, Joomshaper added a **new way to override** Helix3. They are using Jlayouts.

According to the 1.4 changelog, the files have to be placed here: 
/templates/YOUR_TEMPLATE/html/layouts/helix3/frontend/

the original sources are here:  
/plugins/system/helix3/layouts/frontend 

So, you might create overrides for even more than the co**M**ponentarea:
co**n**ponentarea.php
generate.php
modules.php
rows.php  

--- 

PS: I would not dare to use them yet! The changes are pretty new and hence the "typo" in the first file ;)
